### ISSUE TITLE
There are some errors

### ISSUE THREAD

**Issue by Misaka18906** [Mashiro2000/YiBanClockIn#1]
This script is amazing but the following errors occur when there are more and more users.

1. future: <Task finished name='Task-18' coro=<AioYiBan.start() done, defined at AioYiBan.py:490> exception=ServerDisconnectedError('Server disconnected')>(often occur)
2. future: <Task finished name='Task-20' coro=<AioYiBan.start() done, defined at AioYiBan.py:490> exception=KeyError('Location')>

I think is the script running too fast? YiBan Potato Server refused to connect.

**Comment by Mashiro2000** [comment]
It may be the same IP
Or increase the sleep time
in [L243](https://github.com/Mashiro2000/YiBanClockIn/blob/main/AioYiBan.py#L243) and [L246](https://github.com/Mashiro2000/YiBanClockIn/blob/main/AioYiBan.py#L246)

**Comment by Misaka18906** [comment]
I've tried to increase sleep time, but it didn't work.
Just now, I increase the sleep time to 5, there was no error.

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Mashiro2000"; 
Date: 2022年3月28日(星期一) 晚上10:39
To: "Mashiro2000/YiBanClockIn"; 
Cc: ***@***.***>; "Author"; 
Subject: Re: [Mashiro2000/YiBanClockIn] There are some errors (Issue #1)

&nbsp;


 
be on  the cards
 It may be the same IP
 Or increase the sleep time
 1and2

**Comment by Mashiro2000** [comment]
The program uses asynchronous IO
It won't be a waste of time

**Comment by Misaka18906** [comment]
Yes, the script&nbsp; is very easy to use. Thanks again&nbsp;
